apiVersion: v1
kind: Service
metadata:
 name: wordpress-loadbalancer
spec:
 type: LoadBalancer
 selector:
    app: my-wordpress # Busca a partir del laberl app: my-wordpres
 ports:
  - name: "80"
    port: 8080
    targetPort: 80